/* Copyright 2020 @toastedmangoes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
 #include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [0] = LAYOUT_absolem(
         MT(MOD_LGUI,KC_Q),
      MT(MOD_LALT,KC_W),
      MT(MOD_LCTL,KC_F),
      MT(MOD_LSFT,KC_P),
      KC_B,
      KC_J,
      MT(MOD_LSFT | MOD_RSFT,KC_L),
      MT(MOD_LCTL | MOD_RCTL,KC_U),
      MT(MOD_LALT | MOD_RALT,KC_Y),
      MT(MOD_LGUI | MOD_RGUI,KC_SCLN),
      KC_A,
      KC_R,
      KC_S,
      KC_T,
      KC_G,
      KC_M,
      KC_N,
      KC_E,
      KC_I,
      KC_O,
      KC_Z,
      KC_X,
      KC_C,
      KC_D,
      KC_V,
      KC_K,
      KC_H,
      KC_COMM,
      KC_DOT,
      KC_SLSH,
      LT(1,KC_TAB),
      LT(3,KC_BSPC),
      KC_DEL,
      KC_ESC,
      LT(2,KC_SPC),
      LT(1,KC_ENT)
  ),

  [1] = LAYOUT_absolem(
        MT(MOD_LGUI,KC_TILD),
      MT(MOD_LALT,KC_LPRN),
      MT(MOD_LCTL,KC_MNXT),
      MT(MOD_LSFT,KC_RPRN),
      KC_VOLU,
      KC_NO,
      MT(MOD_LSFT | MOD_RSFT,KC_UNDS),
      MT(MOD_LCTL | MOD_RCTL,KC_PLUS),
      KC_RALT,
      KC_RGUI,
      KC_NO,
      KC_LBRC,
      KC_MPLY,
      KC_RBRC,
      KC_MUTE,
      KC_NO,
      KC_MINS,
      KC_EQL,
      KC_NO,
      KC_DQT,
      KC_NO,
      KC_LCBR,
      KC_MPRV,
      KC_RCBR,
      KC_VOLD,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_PIPE,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS
  ), 


  [2] = LAYOUT_absolem(
    MT(MOD_LGUI,KC_GRV),
      MT(MOD_LALT,KC_7),
      MT(MOD_LCTL,KC_8),
      MT(MOD_LSFT,KC_9),
      KC_PPLS,
      KC_F12,
      MT(MOD_LSFT | MOD_RSFT,KC_F7),
      MT(MOD_LCTL | MOD_RCTL,KC_F8),
      MT(MOD_LALT | MOD_RALT,KC_F9),
      KC_TRNS,
      KC_MINS,
      KC_4,
      KC_5,
      KC_6,
      KC_0,
      KC_F11,
      KC_F4,
      KC_F5,
      KC_F6,
      KC_QUOT,
      KC_PSLS,
      KC_1,
      KC_2,
      KC_3,
      KC_PAST,
      KC_F10,
      KC_F1,
      KC_F2,
      KC_F3,
      KC_BSLS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS
  ),

  [3] = LAYOUT_absolem(
    KC_LGUI,
      KC_LALT,
      KC_LCTL,
      KC_LSFT,
      KC_NO,
      KC_NO,
      KC_BSPC,
      KC_INS,
      KC_DEL,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_CAPS,
      KC_ESC,
      KC_LEFT,
      KC_DOWN,
      KC_UP,
      KC_RGHT,
      KC_NO,
      TO(0),
      TO(1),
      TO(2),
      TO(3),
      KC_NO,
      KC_HOME,
      KC_PGDN,
      KC_PGUP,
      KC_END,
      KC_PSCR,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS
  ),

  [4] = LAYOUT_absolem(
    KC_LGUI,
      KC_LALT,
      KC_LCTL,
      KC_LSFT,
      KC_NO,
      KC_NO,
      KC_BSPC,
      KC_INS,
      KC_DEL,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_CAPS,
      KC_ESC,
      KC_LEFT,
      KC_DOWN,
      KC_UP,
      KC_RGHT,
      KC_NO,
      TO(0),
      TO(1),
      TO(2),
      TO(3),
      KC_NO,
      KC_HOME,
      KC_PGDN,
      KC_PGUP,
      KC_END,
      KC_PSCR,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS
  ),

  [5] = LAYOUT_absolem(
    KC_LGUI,
      KC_LALT,
      KC_LCTL,
      KC_LSFT,
      KC_NO,
      KC_NO,
      KC_BSPC,
      KC_INS,
      KC_DEL,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_CAPS,
      KC_ESC,
      KC_LEFT,
      KC_DOWN,
      KC_UP,
      KC_RGHT,
      KC_NO,
      TO(0),
      TO(1),
      TO(2),
      TO(3),
      KC_NO,
      KC_HOME,
      KC_PGDN,
      KC_PGUP,
      KC_END,
      KC_PSCR,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS,
      KC_TRNS
  )
};
