#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#undef MOUSEKEY_WHEEL_INTERVAL
#undef MOUSEKEY_WHEEL_MAX_SPEED

#define MOUSEKEY_INTERVAL          28
#define MOUSEKEY_MAX_SPEED         8
#define MOUSEKEY_TIME_TO_MAX       40
#define MOUSEKEY_WHEEL_TIME_TO_MAX 60
#define MOUSEKEY_WHEEL_INTERVAL    125
#define MOUSEKEY_WHEEL_MAX_SPEED   6

#include "../../config.h"

#endif
